### ISSUE TITLE
Raycast very inefficient, should use multiple body_test_move

### ISSUE THREAD

**Issue by Andicraft** [JheKWall/Godot-Stair-Step-Demo#1]
Hey! I wasn't sure how to best contact you about this - didn't really wanna send an email to your school address - but I found your repository very useful in conceptualizing what I needed to do to get stairs working in Godot, as my previous RaySeparationShape3D approach wasn't... super great, as it involved moving the separationshape when hitting a wall (so if your controller used acceleration you would stop every time you hit a step).

I did rewrite this in C# and I thought it might be useful for you to see my approach as well - the entirety of the code is in [this gist](https://gist.github.com/Andicraft/004cdff7d79947d946887859bac50382).

It simplifies the logic a _lot_ and requires nothing more of your player scene than having a collider named 'Collider', and should avoid missing any gaps. It should work with any collider shapes, though I personally only tested it with a Cylinder using Jolt (but no sphere on the bottom!). It's also completely independent of player height.

The final usage is the same as yours - after all the character movement code we simply call:

```
StairStepUp();
MoveAndSlide();
StairStepDown();
```

I hope this helps, and thank you for this repo - it was helpful for me to think about how to solve this.

**Comment by JheKWall** [comment]
I'm glad this project helped! Your original stairs-character addon is what inspired me to make this one (cause I was having the same problems with the separation ray :sweat_smile:). I've been trying to rework this into only using body_test_motion to mixed results so I'm happy that you've managed to get it to work. I'll see about implementing this into the addon (If you don't mind of course) once I have the time to do so.

**Comment by Andicraft** [comment]
Haha, I'm glad we could inspire each other. And of course, feel free to use the code I wrote!

I'll probably update my own stairs character addon to use this approach, too, now that I know it's working.

**Comment by Andicraft** [comment]
Both my repositories have been updated with my new approach, but there are still some minor issues... and then I found this: http://www.footnotesforthefuture.com/words/godot-movement-manifesto/

Thought it might be of interest. My username on Discord is 'andicraft' if you'd like to talk about this further in the future, so I don't have to abuse the issues feature 😅

**Comment by JheKWall** [comment]
I've sent a friend request! Sorry I haven't been active lately, my classes have been getting in the way of things.

**Comment by JheKWall** [comment]
Thanks for your help! Commit 61cb0c9 is now raycast-free!
